version: "3.7"

services:
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongo/data/db:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server:/app/src/server
    ports:
      - "4000:4000"
    container_name: server
    restart: unless-stopped
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src/client/src
      - /app/src/client/node_modules
    ports:
      - "3000:3000"
    container_name: client
    restart: unless-stopped
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
      - client